version: "3.9"

services:
  server:
    image: gurinderbhogal/note_app:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
